[package]
name = "SPIRE"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simba = "0.7.1"
nalgebra = "0.31.0"
